### ISSUE TITLE
仮想通貨の値動きを確認するツール

### ISSUE THREAD

**Issue by ghost** [vouquet/vouquet#6]
- [Trading View](https://jp.tradingview.com/crypto-screener/)
    - crypto だけでなく株とかも見れる
    - 取引所に関係なくこれだけで全ての crypto が確認できる
    - インジケータがあるので、ニュースとかもこれでみることができそう
       - これだけに依存するかは要検討
    - [REST API](https://jp.tradingview.com/rest-api-spec/)

**Comment by hinoshiba** [comment]
さっきサンプルで展開してもらったのもはっておく
https://etherscan.io/charts

**Comment by ghost** [comment]
> さっきサンプルで展開してもらったのもはっておく
> https://etherscan.io/charts

Ethereum限定。コイン毎にAPIが分かれてる

**Comment by ghost** [comment]
btc
https://www.blockchain.com/en/stats
https://www.blockchain.com/api

**Comment by ghost** [comment]
xmr
https://moneroblocks.info/stats
https://moneroblocks.info/api

最悪なのはmining pool 毎にAPIがあるケース。
https://xmr.nanopool.org/stats
たぶん、現在の主要なmining poolをウォッチしつつ、いくつかのmining pool のapiを叩くようになる。主要なmining pool は変動する。

**Comment by ghost** [comment]
https://crypto-times.jp/coingecko-crypto-derivatives/
先物

**Comment by ghost** [comment]
コインのステークホルダーの状態が監視できるという観点が必要になるかな。

- 直接的
    - マイナー
        - 投資スタイルの一つ
    - ユーザ
        - 現物資産の購入や通貨のやり取りする人
    - 投資家
        - 投資スタイル
            - FX
            - レバレッジ
            - アービトラージ
- 間接的（後々）
    - 同種
        - 派生コイン
        - 対立コイン
    - 異種
        - マイニングの観点
        - peg
        - 思想
